apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/soupvier/x-dev.git
      revision: HEAD
      files:
      - path: applications/*
      # directories:
      # - path: applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/soupvier/x-dev.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: helmfile
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
